FROM python:slim
COPY ./src/app.py /app/
WORKDIR /app
# RUN pip install --no-cache-dir -r requirements.txt 
RUN pip install --no-cache-dir flask
EXPOSE 5000 
ENTRYPOINT [ "python" ] 
CMD [ "app.py" ]

# docker build -t flask_app .
# docker run -dit --name flask_app -p 5000:5000 flask_app
# docker run -dit -v ${pwd}/dist:/app --name flask_app -p 5000:5000 flask_app